<?php

$labels = array();
$labels['fetchmail'] = 'Fetchmail';
$labels['fetchmailtyp'] = 'Typ';
$labels['fetchmailserver'] = 'POP3/IMAP Server';
$labels['fetchmaildelete'] = 'Mails nach Empfang löschen';
$labels['fetchmailenabled'] = 'Aktivieren';
$labels['nofetch'] = 'Keine Einträge vorhanden';
$labels['fetchmail_entries'] = 'Vorhandene Einträge';

$messages = array();
$messages['fetchmaildelconfirm'] = 'Wollen Sie diesen Eintrag wirklich löschen?';
$messages['fetchmaillimitreached'] = 'Limit erreicht';
$messages['textempty'] = 'Ein oder mehrere Felder sind leer';
$messages['opnotpermitted'] = 'Operation nicht gestattet!';
$messages['fetchmailnewentry'] = 'Als neuen Eintrag speichern';
$messages['fetchmailabort'] = 'Abbrechen';
$messages['successfullysaved'] = 'Erfolgreich gespeichert!';
$messages['successfullyenabled'] = 'Erfolgreich aktiviert!';
$messages['successfullydisabled'] = 'Erfolgreich deaktiviert!';
$messages['successfullydeleted'] = 'Erfolgreich gelöscht!';

?>