<?php

$labels = array();
$labels['fetchmail'] = 'Fetchmail';
$labels['fetchmailtyp'] = 'Type';
$labels['fetchmailserver'] = 'POP3/IMAP Server';
$labels['fetchmaildelete'] = 'Delete emails after receiving';
$labels['fetchmailenabled'] = 'Enable';
$labels['nofetch'] = 'No entries available';
$labels['fetchmail_entries'] = 'Available entries';

$messages = array();
$messages['fetchmaildelconfirm'] = 'Do you want to delete this entry?';
$messages['fetchmaillimitreached'] = 'Limit reached';
$messages['textempty'] = 'One or more fields are empty';
$messages['opnotpermitted'] = 'Operation not permitted!';
$messages['fetchmailnewentry'] = 'Save as new';
$messages['fetchmailabort'] = 'Cancel';
$messages['successfullysaved'] = 'Saved successfully!';
$messages['successfullyenabled'] = 'Enabled successfully!';
$messages['successfullydisabled'] = 'Disabled successfully!';
$messages['successfullydeleted'] = 'Deleted successfully!';

?>
