<?php

$labels = array();
$labels['fetchmail'] = 'Fetchmail';
$labels['fetchmailtyp'] = 'Вид сервера';
$labels['fetchmailserver'] = 'Сервер POP3/IMAP';
$labels['fetchmaildelete'] = 'После сборки удалить';
$labels['fetchmailenabled'] = 'Включить';
$labels['nofetch'] = 'Нет записей';
$labels['fetchmail_entries'] = 'Записи';

$messages = array();
$messages['fetchmaildelconfirm'] = 'Вы хотите действительно удалить эту запись?';
$messages['fetchmaillimitreached'] = 'Вы достиги ограничение';
$messages['textempty'] = 'Одно или несколько полей не заполнено';
$messages['opnotpermitted'] = 'Эта операция не допускается!';
$messages['fetchmailnewentry'] = 'Сохранить как новыю запись';
$messages['fetchmailabort'] = 'Отменить';
$messages['successfullysaved'] = 'Успешно сохранено!';
$messages['successfullyenabled'] = 'Успешно включено!';
$messages['successfullydisabled'] = 'Успешно выключено!';
$messages['successfullydeleted'] = 'Успешно удалено!';

?>
